# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-19 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0002_auto_20190819_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('actionid', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='动作ID')),
                ('name', models.CharField(max_length=20, verbose_name='动作名称')),
                ('memo', models.CharField(max_length=20, verbose_name='备忘录')),
            ],
            options={
                'verbose_name_plural': '击球动作',
                'verbose_name': '击球动作',
            },
        ),
        migrations.CreateModel(
            name='Arrange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='动作ID')),
                ('name', models.CharField(max_length=20, verbose_name='动作名称')),
                ('timepoint', models.CharField(max_length=20, verbose_name='时间点')),
                ('place', models.CharField(max_length=20, verbose_name='地点')),
                ('content', models.CharField(max_length=200, verbose_name='训练内容')),
            ],
            options={
                'verbose_name_plural': '训练计划安排',
                'verbose_name': '训练计划安排',
            },
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athleteid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='运动员ID'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coachid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='教练员ID'),
        ),
        migrations.AddField(
            model_name='arrange',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员'),
        ),
        migrations.AddField(
            model_name='arrange',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Coach', verbose_name='教练员'),
        ),
    ]
