# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-21 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motiondata', '0001_initial'),
        ('baseinform', '0007_auto_20190819_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curve_fit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='测试日期')),
                ('pos_x', models.FloatField(verbose_name='关节位移曲线相似度x')),
                ('pos_y', models.FloatField(verbose_name='关节位移曲线相似度y')),
                ('pos_z', models.FloatField(verbose_name='关节位移曲线相似度z')),
                ('rot_x', models.FloatField(verbose_name='关节角度曲线相似x')),
                ('rot_y', models.FloatField(verbose_name='关节角度曲线相似y')),
                ('rot_z', models.FloatField(verbose_name='关节角度曲线相似z')),
                ('pos_x_p1', models.FloatField(verbose_name='引拍阶段位移曲线相似度x')),
                ('pos_y_p1', models.FloatField(verbose_name='引拍阶段位移曲线相似度y')),
                ('pos_z_p1', models.FloatField(verbose_name='引拍阶段位移曲线相似度z')),
                ('pos_x_p2', models.FloatField(verbose_name='挥拍击阶段位移曲线相似度x')),
                ('pos_y_p2', models.FloatField(verbose_name='挥拍击阶段位移曲线相似度y')),
                ('pos_z_p2', models.FloatField(verbose_name='挥拍击阶段位移曲线相似度z')),
                ('pos_x_p3', models.FloatField(verbose_name='还原阶段位移曲线相似度x')),
                ('pos_y_p3', models.FloatField(verbose_name='还原阶段位移曲线相似度y')),
                ('pos_z_p3', models.FloatField(verbose_name='还原阶段位移曲线相似度z')),
                ('rot_x_p1', models.FloatField(verbose_name='引拍阶段角度曲线相似度x')),
                ('rot_y_p1', models.FloatField(verbose_name='引拍阶段角度曲线相似度y')),
                ('rot_z_p1', models.FloatField(verbose_name='引拍阶段角度曲线相似度z')),
                ('rot_x_p2', models.FloatField(verbose_name='挥拍击阶段角度曲线相似度x')),
                ('rot_y_p2', models.FloatField(verbose_name='挥拍击阶段角度曲线相似度y')),
                ('rot_z_p2', models.FloatField(verbose_name='挥拍击阶段角度曲线相似度z')),
                ('rot_x_p3', models.FloatField(verbose_name='还原阶段角度曲线相似度x')),
                ('rot_y_p3', models.FloatField(verbose_name='还原阶段角度曲线相似度y')),
                ('rot_z_p3', models.FloatField(verbose_name='还原阶段角度曲线相似度z')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='击球动作')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motiondata.Joint', verbose_name='关节')),
            ],
            options={
                'verbose_name_plural': '击球动作曲线与优秀运动员的相似度数据',
                'verbose_name': '击球动作曲线与优秀运动员的相似度数据',
            },
        ),
        migrations.CreateModel(
            name='Striking_effect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='测试日期')),
                ('spin', models.FloatField(verbose_name='转速')),
                ('speed', models.FloatField(verbose_name='球速')),
                ('point', models.IntegerField(choices=[(-1, '出界'), (0, '下网'), (1, '上台'), (2, '大区'), (3, '小区')], verbose_name='转速')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='击球动作')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name_plural': '击球质量数据',
                'verbose_name': '击球质量数据',
            },
        ),
    ]
