# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0008_auto_20190824_1638'),
        ('strike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='测试日期')),
                ('speedx', models.FloatField(verbose_name='线速度x')),
                ('speedy', models.FloatField(verbose_name='线速度y')),
                ('speedz', models.FloatField(verbose_name='线速度z')),
                ('displacementx', models.FloatField(verbose_name='位移x')),
                ('displacementy', models.FloatField(verbose_name='位移y')),
                ('displacementz', models.FloatField(verbose_name='位移z')),
                ('sportworkx', models.FloatField(verbose_name='功x')),
                ('sportworky', models.FloatField(verbose_name='功y')),
                ('sportworkz', models.FloatField(verbose_name='功z')),
                ('mark', models.IntegerField(verbose_name='标识')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='击球动作')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name_plural': '击球力量数据分析',
                'verbose_name': '击球力量数据分析',
            },
        ),
        migrations.CreateModel(
            name='Force_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='测试日期')),
                ('ax', models.FloatField(verbose_name='线加速度x')),
                ('ay', models.FloatField(verbose_name='线加速度y')),
                ('az', models.FloatField(verbose_name='线加速度z')),
                ('anglex', models.FloatField(verbose_name='角加速度x')),
                ('angley', models.FloatField(verbose_name='角加速度y')),
                ('anglez', models.FloatField(verbose_name='角加速度z')),
                ('avx', models.FloatField(verbose_name='线速度x')),
                ('avy', models.FloatField(verbose_name='线速度y')),
                ('avz', models.FloatField(verbose_name='线速度z')),
                ('magnetismx', models.FloatField(verbose_name='地磁x')),
                ('magnetismy', models.FloatField(verbose_name='地磁y')),
                ('magnetismz', models.FloatField(verbose_name='地磁z')),
                ('temperature', models.FloatField(verbose_name='温度')),
                ('mark', models.IntegerField(verbose_name='标识')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='击球动作')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name_plural': '击球力量原始数据',
                'verbose_name': '击球力量原始数据',
            },
        ),
        migrations.RemoveField(
            model_name='curve_fit',
            name='action',
        ),
        migrations.RemoveField(
            model_name='curve_fit',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='curve_fit',
            name='joint',
        ),
        migrations.RemoveField(
            model_name='striking_effect',
            name='action',
        ),
        migrations.RemoveField(
            model_name='striking_effect',
            name='athlete',
        ),
        migrations.DeleteModel(
            name='Curve_fit',
        ),
        migrations.DeleteModel(
            name='Striking_effect',
        ),
    ]
