# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-25 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0002_auto_20190824_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='action',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='athlete',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
