# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-24 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strike2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curve_fit',
            name='action',
        ),
        migrations.RemoveField(
            model_name='curve_fit',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='curve_fit',
            name='joint',
        ),
        migrations.DeleteModel(
            name='Curve_fit',
        ),
    ]
