# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike2', '0002_auto_20190824_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='striking_effect',
            name='point',
            field=models.IntegerField(choices=[(0, '出界'), (1, '上台'), (2, '大区'), (3, '小区')], verbose_name='落点'),
        ),
    ]
