# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-18 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athleteid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='运动员ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sfzh', models.CharField(max_length=20, verbose_name='身份证号')),
                ('csrq', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('birthplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='出生地')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='居住地')),
                ('grade', models.CharField(blank=True, max_length=200, null=True, verbose_name='运动员等级')),
                ('years', models.IntegerField(verbose_name='运动年限')),
                ('dflx', models.CharField(blank=True, max_length=200, null=True, verbose_name='打法类型')),
                ('bscj', models.CharField(blank=True, max_length=200, null=True, verbose_name='比赛成绩')),
                ('entrance_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='入队年份')),
                ('retired', models.CharField(choices=[('true', '已经离队'), ('false', '未离队')], default='false', max_length=2, verbose_name='是否离队')),
            ],
            options={
                'verbose_name_plural': '运动员',
                'verbose_name': '运动员',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coachid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='教练员ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=6)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='居住地')),
                ('grade', models.CharField(blank=True, max_length=200, null=True, verbose_name='教练员等级')),
                ('years', models.IntegerField(verbose_name='执教年数')),
            ],
            options={
                'verbose_name_plural': '教练员',
                'verbose_name': '教练员',
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Coach', verbose_name='教练员'),
        ),
    ]
