# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-19 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='retired',
            field=models.CharField(choices=[('true', '已经离队'), ('false', '未离队')], default='false', max_length=5, verbose_name='是否离队'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
