# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0004_remove_arrange_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Force_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(blank=True, null=True, verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='测试日期')),
                ('ax', models.FloatField(verbose_name='线加速度x')),
                ('ay', models.FloatField(verbose_name='线加速度y')),
                ('az', models.FloatField(verbose_name='线加速度z')),
                ('anglex', models.FloatField(verbose_name='角加速度x')),
                ('angley', models.FloatField(verbose_name='角加速度y')),
                ('anglez', models.FloatField(verbose_name='角加速度z')),
                ('avx', models.FloatField(verbose_name='线速度x')),
                ('avy', models.FloatField(verbose_name='线速度y')),
                ('avz', models.FloatField(verbose_name='线速度z')),
                ('magnetismx', models.FloatField(verbose_name='地磁x')),
                ('magnetismy', models.FloatField(verbose_name='地磁y')),
                ('magnetismz', models.FloatField(verbose_name='地磁z')),
                ('temperature', models.FloatField(verbose_name='温度')),
                ('mark', models.IntegerField(verbose_name='标识')),
            ],
            options={
                'verbose_name_plural': '击球力量原始数据',
                'verbose_name': '击球力量原始数据',
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='actionid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='动作ID'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athleteid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='运动员ID'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='csrq',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coachid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='教练员ID'),
        ),
        migrations.AddField(
            model_name='force_info',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='击球动作'),
        ),
        migrations.AddField(
            model_name='force_info',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员'),
        ),
    ]
