# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0008_auto_20190824_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在运动队名称'),
        ),
    ]
