# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-01 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0009_coach_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='actionid',
            new_name='action_id',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='athleteid',
            new_name='athlete_id',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='coachid',
            new_name='coach_id',
        ),
        migrations.RenameField(
            model_name='joint',
            old_name='jointid',
            new_name='joint_id',
        ),
    ]
