# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0010_auto_20190901_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='所在运动队名称'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='所在运动队名称'),
        ),
    ]
