# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-02 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0011_auto_20190901_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.CharField(max_length=6, verbose_name='性别'),
        ),
    ]
