# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-21 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinform', '0007_auto_20190819_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Force_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='测试日期')),
                ('Hip', models.IntegerField(verbose_name='髋关节')),
                ('LeftShoulder', models.IntegerField(verbose_name='左肩关节')),
                ('LeftArm', models.IntegerField(verbose_name='左肘关节')),
                ('RightShoulder', models.IntegerField(verbose_name='右肩关节')),
                ('RightArm', models.IntegerField(verbose_name='右肘关节')),
                ('LeftLeg', models.IntegerField(verbose_name='左膝关节')),
                ('LeftFoot', models.IntegerField(verbose_name='左踝关节')),
                ('RightLeg', models.IntegerField(verbose_name='右膝关节')),
                ('RightFoot', models.IntegerField(verbose_name='右踝关节')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='击球动作')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name_plural': '关节点发力顺序数据',
                'verbose_name': '关节点发力顺序数据',
            },
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('jointid', models.IntegerField(primary_key=True, serialize=False, verbose_name='关节ID')),
                ('name', models.CharField(max_length=20, verbose_name='关节名称')),
                ('memo', models.CharField(max_length=20, verbose_name='备忘录')),
            ],
            options={
                'verbose_name_plural': '人体主要关节',
                'verbose_name': '人体主要关节',
            },
        ),
        migrations.CreateModel(
            name='Mtion_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='测试日期')),
                ('frameno', models.IntegerField(verbose_name='帧编号')),
                ('hip_pos_x', models.FloatField(verbose_name='髋关节x轴坐标')),
                ('hip_pos_y', models.FloatField(verbose_name='髋关节y轴坐标')),
                ('hip_pos_z', models.FloatField(verbose_name='髋关节z轴坐标')),
                ('hip_rot_x', models.FloatField(verbose_name='髋关节x轴角度')),
                ('hip_rot_y', models.FloatField(verbose_name='髋关节y轴角度')),
                ('hip_rot_z', models.FloatField(verbose_name='髋关节z轴角度')),
                ('leftshoulder_pos_x', models.FloatField(verbose_name='左肩x轴坐标')),
                ('leftshoulder_pos_y', models.FloatField(verbose_name='左肩y轴坐标')),
                ('leftshoulder_pos_z', models.FloatField(verbose_name='左肩z轴坐标')),
                ('leftshoulder_rot_x', models.FloatField(verbose_name='左肩x轴角度')),
                ('leftshoulder_rot_y', models.FloatField(verbose_name='左肩y轴角度')),
                ('leftshoulder_rot_z', models.FloatField(verbose_name='左肩z轴角度')),
                ('leftarm_pos_x', models.FloatField(verbose_name='左肘x轴角度')),
                ('leftarm_pos_y', models.FloatField(verbose_name='左肘y轴角度')),
                ('leftarm_pos_z', models.FloatField(verbose_name='左肘z轴角度')),
                ('rightshoulder_pos_x', models.FloatField(verbose_name='右肩x轴坐标')),
                ('rightshoulder_pos_y', models.FloatField(verbose_name='右肩y轴坐标')),
                ('rightshoulder_pos_z', models.FloatField(verbose_name='右肩z轴坐标')),
                ('rightshoulder_rot_x', models.FloatField(verbose_name='右肩x轴角度')),
                ('rightshoulder_rot_y', models.FloatField(verbose_name='右肩y轴角度')),
                ('rightshoulder_rot_z', models.FloatField(verbose_name='右肩z轴角度')),
                ('rightarm_pos_x', models.FloatField(verbose_name='右肘x轴坐标')),
                ('rightarm_pos_y', models.FloatField(verbose_name='右肘y轴坐标')),
                ('rightarm_pos_z', models.FloatField(verbose_name='右肘z轴坐标')),
                ('rightarm_rot_x', models.FloatField(verbose_name='右肘x轴角度')),
                ('rightarm_rot_y', models.FloatField(verbose_name='右肘y轴角度')),
                ('rightarm_rot_z', models.FloatField(verbose_name='右肘z轴角度')),
                ('leftleg_pos_x', models.FloatField(verbose_name='左膝x轴坐标')),
                ('leftleg_pos_y', models.FloatField(verbose_name='左膝y轴坐标')),
                ('leftleg_pos_z', models.FloatField(verbose_name='左膝z轴坐标')),
                ('leftleg_rot_y', models.FloatField(verbose_name='左膝y轴角度')),
                ('leftleg_rot_z', models.FloatField(verbose_name='左膝z轴角度')),
                ('leftfoot_pos_x', models.FloatField(verbose_name='左踝x轴坐标')),
                ('leftfoot_pos_y', models.FloatField(verbose_name='左踝y轴坐标')),
                ('leftfoot_pos_z', models.FloatField(verbose_name='左踝z轴坐标')),
                ('leftfoot_rot_x', models.FloatField(verbose_name='左踝x轴角度')),
                ('leftfoot_rot_y', models.FloatField(verbose_name='左踝y轴角度')),
                ('leftfoot_rot_z', models.FloatField(verbose_name='左踝z轴角度')),
                ('rightleg_pos_x', models.FloatField(verbose_name='右膝x轴坐标')),
                ('rightleg_pos_y', models.FloatField(verbose_name='右膝y轴坐标')),
                ('rightleg_pos_z', models.FloatField(verbose_name='右膝z轴坐标')),
                ('rightleg_rot_x', models.FloatField(verbose_name='右膝x轴角度')),
                ('rightleg_rot_y', models.FloatField(verbose_name='右膝y轴角度')),
                ('rightleg_rot_z', models.FloatField(verbose_name='右膝z轴角度')),
                ('rightfoot_pos_x', models.FloatField(verbose_name='右踝x轴坐标')),
                ('rightfoot_pos_y', models.FloatField(verbose_name='右踝y轴坐标')),
                ('rightfoot_pos_z', models.FloatField(verbose_name='右踝z轴坐标')),
                ('rightfoot_rot_x', models.FloatField(verbose_name='右踝x轴角度')),
                ('rightfoot_rot_y', models.FloatField(verbose_name='右踝y轴角度')),
                ('rightfoot_rot_z', models.FloatField(verbose_name='右踝z轴角度')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='击球动作')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name_plural': '动作捕捉原始数据',
                'verbose_name': '动作捕捉原始数据',
            },
        ),
    ]
