# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-24 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0002_auto_20190824_1804'),
        ('motiondata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joint',
        ),
    ]
