# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-01 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motiondata', '0003_curve_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mtion_data',
            new_name='Motion_data',
        ),
    ]
