# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motiondata', '0006_auto_20190901_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curve_model',
            name='rot_x',
            field=models.FloatField(blank=True, null=True, verbose_name='关节x方向角度'),
        ),
        migrations.AlterField(
            model_name='curve_model',
            name='rot_y',
            field=models.FloatField(blank=True, null=True, verbose_name='关节y方向角度'),
        ),
    ]
