# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-02 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motiondata', '0007_auto_20190901_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion_data',
            name='leftleg_rot_x',
            field=models.FloatField(default=1, verbose_name='左膝x轴角度'),
            preserve_default=False,
        ),
    ]
