# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinform', '0008_auto_20190824_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='动作ID')),
                ('timepoint', models.CharField(max_length=20, verbose_name='时间点')),
                ('place', models.CharField(max_length=20, verbose_name='地点')),
                ('content', models.CharField(max_length=200, verbose_name='训练内容')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Coach', verbose_name='教练员')),
            ],
            options={
                'verbose_name': '训练计划安排',
                'verbose_name_plural': '训练计划安排',
            },
        ),
    ]
