# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-25 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinform', '0008_auto_20190824_1638'),
        ('trainingplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrate_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(verbose_name='测试序号')),
                ('testdate', models.DateTimeField(blank=True, null=True, verbose_name='训练日期')),
                ('hr_star', models.FloatField(verbose_name='训练开始心率')),
                ('hr_end', models.FloatField(verbose_name='训练结束心率')),
                ('hr_min', models.FloatField(verbose_name='心率最小值')),
                ('hr_avg', models.FloatField(verbose_name='心率平均值')),
                ('hr_max', models.FloatField(verbose_name='心率最大值')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Action', verbose_name='动作')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name': '训练强度',
                'verbose_name_plural': '训练强度',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('rival', models.CharField(blank=True, max_length=50, null=True, verbose_name='对手名称')),
                ('date', models.DateField(blank=True, null=True, verbose_name='比赛日期')),
                ('mingcheng', models.CharField(blank=True, max_length=50, null=True, verbose_name='比赛名称')),
                ('xiangmu', models.IntegerField(choices=[(1, '单打'), (2, '双打')], verbose_name='项目')),
                ('result', models.CharField(max_length=50, verbose_name='比赛结果：总比分')),
                ('r1', models.CharField(max_length=50, verbose_name='第1局比分')),
                ('r2', models.CharField(max_length=50, verbose_name='第2局比分')),
                ('r3', models.CharField(max_length=50, verbose_name='第3局比分')),
                ('r4', models.CharField(max_length=50, verbose_name='第4局比分')),
                ('r5', models.CharField(max_length=50, verbose_name='第5局比分')),
                ('r6', models.CharField(max_length=50, verbose_name='第6局比分')),
                ('r7', models.CharField(max_length=50, verbose_name='第7局比分')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员姓名')),
            ],
            options={
                'verbose_name': '比赛成绩',
                'verbose_name_plural': '比赛成绩',
            },
        ),
        migrations.CreateModel(
            name='ShenghuaDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='检验日期')),
                ('gaotong', models.FloatField(verbose_name='睾酮')),
                ('pizhichun', models.FloatField(verbose_name='皮质醇')),
                ('niaosudan', models.FloatField(verbose_name='尿素氮')),
                ('tc', models.FloatField(verbose_name='总胆固醇')),
                ('jisuanjimei', models.FloatField(verbose_name='肌酸激酶')),
                ('yichang', models.CharField(blank=True, max_length=50, null=True, verbose_name='异常数据说明')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinform.Athlete', verbose_name='运动员姓名')),
            ],
            options={
                'verbose_name': '生化指标',
                'verbose_name_plural': '生化指标',
            },
        ),
    ]
