# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-01 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplan', '0002_hrate_info_performance_shenghuadate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShenghuaDate',
            new_name='Physiology_test',
        ),
    ]
