# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-15 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplan', '0003_auto_20190901_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrate_info',
            old_name='hr_star',
            new_name='hr_start',
        ),
    ]
